-- Baseline migration for fresh Supabase projects.
-- Generated by consolidating historical migrations in chronological order.
-- Date: 2026-04-07

-- >>> BEGIN 20260320234600_add_user_stats.sql
/* ---- User Stats ----- */
create table public.user_stats (
  user_id uuid primary key references auth.users(id) on delete cascade,
  total_seconds bigint NOT NULL default 0,
  daily_average bigint NOT NULL default 0,
  languages jsonb NOT NULL default '[]'::jsonb,
  operating_systems jsonb NOT NULL default '[]'::jsonb,
  editors jsonb NOT NULL default '[]'::jsonb,
  machines jsonb NOT NULL default '[]'::jsonb,
  categories jsonb NOT NULL default '[]'::jsonb,
  dependencies jsonb NOT NULL default '[]'::jsonb,
  best_day jsonb NOT NULL default '{}'::jsonb,
  daily_stats jsonb NOT NULL default '[]'::jsonb,
  last_fetched_at timestamp with time zone NOT NULL default now()
);

alter table public.user_stats enable row level security;

/* ---- RLS Policy ----- */
create policy "Users can insert their stats"
on public.user_stats
for insert
with check (auth.uid() = user_id);

create policy "Users can update their stats"
on public.user_stats
for update
using (auth.uid() = user_id);

create policy "Authenticated users can view stats"
on public.user_stats
for select
using (auth.role() = 'authenticated');
-- <<< END 20260320234600_add_user_stats.sql

-- >>> BEGIN 20260320234643_add_top_user_stats.sql
CREATE OR REPLACE VIEW top_user_stats AS
SELECT
  us.user_id,
  us.total_seconds,
  a.email
FROM user_stats us
JOIN auth.users a ON us.user_id = a.id;
-- <<< END 20260320234643_add_top_user_stats.sql

-- >>> BEGIN 20260320234653_add_profiles.sql
/* ---- Profile ----- */
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  wakatime_api_key text default null unique,
  created_at timestamp with time zone NOT NULL default now()
);

/* ---- RLS Policies ----- */
alter table public.profiles enable row level security;

create policy "Users can view their own profile"
on public.profiles
for select
using (auth.uid() = id);

create policy "Users can update their own profile"
on public.profiles
for update
using (auth.uid() = id);

create policy "Users can insert their own profile"
on public.profiles
for insert
with check (auth.uid() = id);

/* ---- Auto Create Profile on Signup Trigger ----- */
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do update
  set email = excluded.email;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
-- <<< END 20260320234653_add_profiles.sql

-- >>> BEGIN 20260320234714_add_leaderboards.sql
/* ---- Leaderboards ----- */
create table public.leaderboards (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  is_public boolean NOT NULL default true,
  owner_id uuid NOT NULL references auth.users(id) on delete cascade,
  join_code text not null unique,
  created_at timestamptz NOT NULL default now()
);

alter table public.leaderboards enable row level security;

/* ---- Leaderboards Members ----- */
create table public.leaderboard_members (
  id uuid primary key default gen_random_uuid(),
  leaderboard_id uuid NOT NULL references public.leaderboards(id) on delete cascade,
  user_id uuid NOT NULL references auth.users(id) on delete cascade,
  role text NOT NULL default 'member', -- owner | member
  joined_at timestamptz NOT NULL default now(),
  unique (leaderboard_id, user_id)
);

alter table public.leaderboard_members enable row level security;

/* ---- Leaderboards Members View ----- */
create view public.leaderboard_members_view as
select
  lm.id,
  lm.leaderboard_id,
  lm.user_id,
  lm.role,
  u.email,
  us.total_seconds,
  us.languages,
  us.operating_systems,
  us.editors
from public.leaderboard_members lm
join auth.users u on lm.user_id = u.id
left join public.user_stats us on lm.user_id = us.user_id;

/* ---- RLS Policies ----- */
create policy "Public leaderboards are viewable"
on public.leaderboards
for select
using (is_public = true OR owner_id = auth.uid());

create policy "Users can create leaderboards"
on public.leaderboards
for insert
with check (auth.uid() = owner_id);

create policy "Owner can update leaderboard"
on public.leaderboards
for update
using (auth.uid() = owner_id);

/* ---- Members Policies ----- */
create policy "Users can see memberships for visible leaderboards"
on public.leaderboard_members
for select
using (
  exists (
    select 1
    from public.leaderboards l
    where l.id = leaderboard_members.leaderboard_id
      and (
        l.is_public = true
        or l.owner_id = auth.uid()
        or exists (
          select 1
          from public.leaderboard_members lm
          where lm.leaderboard_id = l.id
            and lm.user_id = auth.uid()
        )
      )
  )
);

create policy "Users can join leaderboard"
on public.leaderboard_members
for insert
with check (auth.uid() = user_id);

create policy "Members can leave leaderboard"
on public.leaderboard_members
for delete
using (user_id = auth.uid());

create policy "Owner can manage members"
on public.leaderboard_members
for delete
using (
  leaderboard_id IN (
    select id
    from public.leaderboards
    where owner_id = auth.uid()
  )
);
-- <<< END 20260320234714_add_leaderboards.sql

-- >>> BEGIN 20260320234731_add_enforcement_checks.sql
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'leaderboards_name_length'
			AND conrelid = 'public.leaderboards'::regclass
	) THEN
		alter table public.leaderboards
		add constraint leaderboards_name_length
		check (length(trim(name)) between 3 and 50);
	END IF;
END
$$;

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'leaderboards_description_length'
			AND conrelid = 'public.leaderboards'::regclass
	) THEN
		alter table public.leaderboards
		add constraint leaderboards_description_length
		check (description is null or length(description) <= 150);
	END IF;
END
$$;

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'leaderboards_join_code_format'
			AND conrelid = 'public.leaderboards'::regclass
	) THEN
		alter table public.leaderboards
		add constraint leaderboards_join_code_format
		check (join_code ~ '^[A-Za-z0-9]{1,8}$');
	END IF;
END
$$;

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_policies
		WHERE schemaname = 'public'
			AND tablename = 'leaderboards'
			AND policyname = 'Owner can delete leaderboard'
	) THEN
		create policy "Owner can delete leaderboard"
		on public.leaderboards
		for delete
		using (auth.uid() = owner_id);
	END IF;
END
$$;
-- <<< END 20260320234731_add_enforcement_checks.sql

-- >>> BEGIN 20260320234742_add_user_projects.sql
/* ---- User Projects Stats ----- */
create table public.user_projects (
  user_id uuid primary key references auth.users(id) on delete cascade,
  projects jsonb default '[]'::jsonb,
  last_fetched_at timestamp with time zone NOT NULL default now()
);

alter table public.user_projects enable row level security;

create policy "Users can view their own projects"
on public.user_projects
for select
using (auth.uid() = user_id);

create policy "Users can insert their own projects"
on public.user_projects
for insert
with check (auth.uid() = user_id);

create policy "Users can update their own projects"
on public.user_projects
for update
using (auth.uid() = user_id);
-- <<< END 20260320234742_add_user_projects.sql

-- >>> BEGIN 20260320234758_add_conversations.sql
/* ---- Conversations ----- */
CREATE TABLE conversations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now()
);

/* ---- Participants ----- */
CREATE TABLE conversation_participants (
  conversation_id uuid NOT NULL REFERENCES conversations(id),
  user_id uuid NOT NULL REFERENCES auth.users(id),
  email text NOT NULL,
  PRIMARY KEY(conversation_id, user_id)
);

/* ---- Messages ----- */
CREATE TABLE messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL REFERENCES conversations(id),
  sender_id uuid NOT NULL REFERENCES auth.users(id),
  text text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.is_conversation_member(
  target_conversation_id uuid,
  target_user_id uuid
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.conversation_participants cp
    WHERE cp.conversation_id = target_conversation_id
      AND cp.user_id = target_user_id
  );
$$;

ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversation_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

/* ---- RLS Policies ----- */
CREATE POLICY "participants can read conversations"
ON conversations
FOR SELECT
USING (public.is_conversation_member(id, auth.uid()));

CREATE POLICY "authenticated users can create conversations"
ON conversations
FOR INSERT
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "participants can update conversations"
ON conversations
FOR UPDATE
USING (public.is_conversation_member(id, auth.uid()));

CREATE POLICY "participants can delete conversations"
ON conversations
FOR DELETE
USING (public.is_conversation_member(id, auth.uid()));

CREATE POLICY "participants can read participant list"
ON conversation_participants
FOR SELECT
USING (public.is_conversation_member(conversation_id, auth.uid()));

CREATE POLICY "users can add self participant row"
ON conversation_participants
FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "participants can add other participants"
ON conversation_participants
FOR INSERT
WITH CHECK (public.is_conversation_member(conversation_id, auth.uid()));

CREATE POLICY "users can update their own participant row"
ON conversation_participants
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "users can remove their own participant row"
ON conversation_participants
FOR DELETE
USING (auth.uid() = user_id);

CREATE POLICY "participants can read messages"
ON messages
FOR SELECT
USING (public.is_conversation_member(conversation_id, auth.uid()));

CREATE POLICY "participants can send messages"
ON messages
FOR INSERT
WITH CHECK (public.is_conversation_member(conversation_id, auth.uid()));
-- <<< END 20260320234758_add_conversations.sql

-- >>> BEGIN 20260321140532_add_categories_to_top_user_stats.sql
CREATE OR REPLACE VIEW top_user_stats AS
SELECT
  us.user_id,
  us.total_seconds,
  a.email,
  us.categories -- new column
FROM user_stats us
JOIN auth.users a ON us.user_id = a.id;
-- <<< END 20260321140532_add_categories_to_top_user_stats.sql

-- >>> BEGIN 20260323033205_add_type_to_conversations.sql
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS type text NOT NULL DEFAULT 'private';
-- <<< END 20260323033205_add_type_to_conversations.sql

-- >>> BEGIN 20260323033729_add_global_chat.sql
-- Add a global conversation
INSERT INTO public.conversations (id, type)
VALUES ('00000000-0000-0000-0000-000000000001', 'global')
ON CONFLICT (id) DO UPDATE
SET type = EXCLUDED.type;

INSERT INTO public.conversation_participants (
	conversation_id,
	user_id,
	email
)
SELECT
	'00000000-0000-0000-0000-000000000001',
	u.id,
	COALESCE(u.email, CONCAT(u.id::text, '@user.local'))
FROM auth.users u
ON CONFLICT (conversation_id, user_id) DO UPDATE
SET email = EXCLUDED.email;
-- <<< END 20260323033729_add_global_chat.sql

-- >>> BEGIN 20260323041448_add_type_to_conversation_participants.sql
ALTER TABLE conversation_participants
ADD COLUMN IF NOT EXISTS type text NOT NULL DEFAULT 'private';

UPDATE conversation_participants
SET type = 'global'
WHERE conversation_id = '00000000-0000-0000-0000-000000000001';
-- <<< END 20260323041448_add_type_to_conversation_participants.sql

-- >>> BEGIN 20260323041543_add_trigger_to_type.sql
CREATE OR REPLACE FUNCTION public.sync_conversation_type()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.type := (
    SELECT c.type
    FROM public.conversations c
    WHERE c.id = NEW.conversation_id
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS conversation_type_trigger ON conversation_participants;

CREATE TRIGGER conversation_type_trigger
BEFORE INSERT ON conversation_participants
FOR EACH ROW
EXECUTE FUNCTION sync_conversation_type();
-- <<< END 20260323041543_add_trigger_to_type.sql

-- >>> BEGIN 20260323075413_add_attachments_to_messages.sql
ALTER TABLE messages
ADD COLUMN IF NOT EXISTS attachments JSONB NOT NULL DEFAULT '[]'::jsonb;

-- allow authenticated users to upload
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_policies
		WHERE schemaname = 'storage'
			AND tablename = 'objects'
			AND policyname = 'Allow uploads by owner'
	) THEN
		CREATE POLICY "Allow uploads by owner"
		ON storage.objects
		FOR INSERT
		TO authenticated
		WITH CHECK (auth.uid() = owner);
	END IF;
END
$$;
-- <<< END 20260323075413_add_attachments_to_messages.sql

-- >>> BEGIN 20260325044133_add_user_flexes.sql
create table public.user_flexes (
  id uuid primary key default gen_random_uuid(),
    user_id uuid NOT NULL references auth.users(id) on delete cascade,
  user_email text NOT NULL,
  project_name text NOT NULL,
  project_description text NOT NULL,
  project_url text NOT NULL,
  project_time text NOT NULL,
  is_open_source boolean NOT NULL default false,
  open_source_url text NOT NULL default '',
  created_at timestamp with time zone NOT NULL default now()
);

alter table public.user_flexes enable row level security;

/* ---- RLS Policy ----- */
create policy "Public Access" on public.user_flexes
for select
using (true);

create policy "User Flexes" on public.user_flexes
for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create or replace function flex_project(p_user_id uuid, p_project jsonb)
returns text as $$
declare
        v_project_name text;
        v_project_description text;
        v_project_url text;
        v_project_time text;
        v_is_open_source boolean;
        v_open_source_url text;
        v_user_email text;
begin
        v_project_name := coalesce(
            nullif(trim(p_project->>'project_name'), ''),
            nullif(trim(p_project->>'name'), '')
        );
        v_project_description := coalesce(nullif(trim(p_project->>'project_description'), ''), '');
        v_project_url := coalesce(nullif(trim(p_project->>'project_url'), ''), '');
        v_project_time := coalesce(
            nullif(trim(p_project->>'project_time'), ''),
            nullif(trim(p_project->>'text'), ''),
            ''
        );
        v_is_open_source := lower(coalesce(p_project->>'is_open_source', 'false')) in ('true', '1', 't', 'yes', 'y');
        v_open_source_url := coalesce(nullif(trim(p_project->>'open_source_url'), ''), '');
        v_user_email := coalesce(nullif(trim(p_project->>'user_email'), ''), concat(p_user_id::text, '@user.local'));

        if v_project_name is null then
                return 'Project name is required';
        end if;

    if exists (
        select 1
        from public.user_flexes
        where user_id = p_user_id
                    and created_at > now() - interval '24 hours'
    ) then
        return 'You can only flex once every 24 hours';
    else
                insert into public.user_flexes(
                    user_id,
                    user_email,
                    project_name,
                    project_description,
                    project_url,
                    project_time,
                    is_open_source,
                    open_source_url
                )
                values (
                    p_user_id,
                    v_user_email,
                    v_project_name,
                    v_project_description,
                    v_project_url,
                    v_project_time,
                    v_is_open_source,
                    v_open_source_url
                );
        return 'Project flexed successfully!';
    end if;
end;
$$ language plpgsql security definer set search_path = public;
-- <<< END 20260325044133_add_user_flexes.sql

-- >>> BEGIN 20260325054413_add_expires_at_user_flexes.sql
alter table public.user_flexes
add column if not exists expires_at timestamp with time zone;

update public.user_flexes
set expires_at = coalesce(expires_at, created_at + interval '24 hours');

alter table public.user_flexes
alter column expires_at set default (now() + interval '24 hours');

alter table public.user_flexes
alter column expires_at set not null;
-- <<< END 20260325054413_add_expires_at_user_flexes.sql

-- >>> BEGIN 20260325072343_add_role_to_profiles.sql
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT 'user';

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'profiles_role_check'
			AND conrelid = 'public.profiles'::regclass
	) THEN
		ALTER TABLE public.profiles
		ADD CONSTRAINT profiles_role_check
		CHECK (role IN ('user', 'admin'));
	END IF;
END
$$;
-- <<< END 20260325072343_add_role_to_profiles.sql

-- >>> BEGIN 20260327100000_cascade_conversation_delete.sql
DO $$
BEGIN
  -- Drop existing constraints if they exist
  ALTER TABLE conversation_participants DROP CONSTRAINT IF EXISTS conversation_participants_conversation_id_fkey;
  ALTER TABLE messages DROP CONSTRAINT IF EXISTS messages_conversation_id_fkey;

  -- Add constraints with cascade
  ALTER TABLE conversation_participants ADD CONSTRAINT conversation_participants_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
  ALTER TABLE messages ADD CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
END $$;
-- <<< END 20260327100000_cascade_conversation_delete.sql

-- >>> BEGIN 20260329120000_add_user_dashboard_snapshots.sql
/* ---- User Dashboard Snapshots ----- */
create table public.user_dashboard_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  snapshot_date date not null,
  total_seconds_7d bigint not null default 0,
  active_days_7d integer not null default 0,
  consistency_percent integer not null default 0,
  current_streak integer not null default 0,
  best_streak integer not null default 0,
  peak_day date,
  peak_day_seconds bigint not null default 0,
  top_language text,
  top_language_percent numeric(5,2),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (user_id, snapshot_date),
  check (active_days_7d between 0 and 7),
  check (consistency_percent between 0 and 100),
  check (peak_day_seconds >= 0),
  check (
    top_language_percent is null
    or (top_language_percent >= 0 and top_language_percent <= 100)
  )
);

alter table public.user_dashboard_snapshots enable row level security;

create policy "Users can view their own dashboard snapshots"
on public.user_dashboard_snapshots
for select
using (auth.uid() = user_id);

create policy "Users can insert their own dashboard snapshots"
on public.user_dashboard_snapshots
for insert
with check (auth.uid() = user_id);

create policy "Users can update their own dashboard snapshots"
on public.user_dashboard_snapshots
for update
using (auth.uid() = user_id);
-- <<< END 20260329120000_add_user_dashboard_snapshots.sql

-- >>> BEGIN 20260329133000_add_chat_presence_and_read_tracking.sql
ALTER TABLE conversation_participants
ADD COLUMN IF NOT EXISTS last_seen_at timestamptz NOT NULL DEFAULT to_timestamp(0),
ADD COLUMN IF NOT EXISTS last_read_at timestamptz NOT NULL DEFAULT now();

UPDATE conversation_participants
SET
  last_seen_at = COALESCE(last_seen_at, to_timestamp(0)),
  last_read_at = COALESCE(last_read_at, now());

CREATE INDEX IF NOT EXISTS idx_conversation_participants_user_last_seen_at
ON conversation_participants (user_id, last_seen_at DESC);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_created_sender
ON messages (conversation_id, created_at DESC, sender_id);
-- <<< END 20260329133000_add_chat_presence_and_read_tracking.sql

-- >>> BEGIN 20260330103000_enable_chat_realtime_publication.sql
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'conversations'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.conversations;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'conversation_participants'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.conversation_participants;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'messages'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
  END IF;
END
$$;
-- <<< END 20260330103000_enable_chat_realtime_publication.sql

-- >>> BEGIN 20260330104500_fix_global_chat_membership.sql
-- Ensure the global conversation row exists and has the expected type.
INSERT INTO public.conversations (id, type)
VALUES ('00000000-0000-0000-0000-000000000001', 'global')
ON CONFLICT (id) DO UPDATE
SET type = EXCLUDED.type;

-- Backfill global chat membership for all existing auth users.
INSERT INTO public.conversation_participants (conversation_id, user_id, email)
SELECT
  '00000000-0000-0000-0000-000000000001',
  u.id,
  COALESCE(u.email, CONCAT(u.id::text, '@user.local'))
FROM auth.users u
ON CONFLICT (conversation_id, user_id) DO UPDATE
SET email = EXCLUDED.email;

-- Keep future auth users automatically enrolled in global chat.
CREATE OR REPLACE FUNCTION public.ensure_user_in_global_chat()
RETURNS TRIGGER AS $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.conversations
    WHERE id = '00000000-0000-0000-0000-000000000001'
  ) THEN
    INSERT INTO public.conversation_participants (conversation_id, user_id, email)
    VALUES (
      '00000000-0000-0000-0000-000000000001',
      NEW.id,
      COALESCE(NEW.email, CONCAT(NEW.id::text, '@user.local'))
    )
    ON CONFLICT (conversation_id, user_id) DO UPDATE
    SET email = EXCLUDED.email;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS on_auth_user_join_global_chat ON auth.users;

CREATE TRIGGER on_auth_user_join_global_chat
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.ensure_user_in_global_chat();
-- <<< END 20260330104500_fix_global_chat_membership.sql

